version: '3.9'

services:
  pg:
    image: postgres:13-alpine
    container_name: pg_app
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    restart: always

  redis:
     image: redis:7
     container_name: redis_app
     env_file:
      - .env

  app:
    build:
      context: .
    env_file:
      - .env
    container_name: bcs_app
    command: ["/app/docker/app.sh"]
    depends_on:
      - pg
      - redis
    ports:
      - "8000:8000"
