"""add_parent_id_to_department

Revision ID: 1c9ff95ee253
Revises: 9fde9cc10e7f
Create Date: 2024-08-03 16:27:30.900154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c9ff95ee253'
down_revision: Union[str, None] = '9fde9cc10e7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'departments', 'departments', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.drop_column('departments', 'parent_id')
    # ### end Alembic commands ###
