"""update department model for ltree with foreign and remote

Revision ID: b9924f3a94ca
Revises: d21727d2375d
Create Date: 2024-07-24 13:41:11.244105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9924f3a94ca'
down_revision: Union[str, None] = 'd21727d2375d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
